"""Initial schema

Revision ID: 6d7679cd0cf1
Revises: 
Create Date: 2026-09-11 14:13:11.753844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d7679cd0cf1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bidders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('legal_name', sa.String(), nullable=True),
    sa.Column('pan', sa.String(), nullable=True),
    sa.Column('is_demo_profile', sa.Boolean(), nullable=True),
    sa.Column('demo_profile_key', sa.String(), nullable=True),
    sa.Column('local_content_pct_declared', sa.Numeric(), nullable=True),
    sa.Column('annual_turnover_inr', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'open', 'evaluation', 'closed', name='tender_status_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('officer', 'bidder', 'admin', name='user_role_enum'), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bid_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Enum('document_upload', 'document_correction', 'evaluation_run', 'decision_submitted', name='event_type_enum'), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bidder_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bidder_id', sa.UUID(), nullable=True),
    sa.Column('doc_type', sa.Enum('pan', 'gst_certificate', 'udyam_certificate', 'epfo_esic', 'other', name='doc_type_enum'), nullable=True),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('ocr_status', sa.Enum('pending', 'processing', 'done', 'failed', name='ocr_status_enum'), nullable=True),
    sa.Column('extracted_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confirmed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bidder_id'], ['bidders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bid_id', sa.UUID(), nullable=True),
    sa.Column('tender_id', sa.UUID(), nullable=True),
    sa.Column('bidder_id', sa.UUID(), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', name='risk_level_enum'), nullable=True),
    sa.Column('verdict', sa.Enum('compliant', 'non_compliant', 'needs_review', name='verdict_enum'), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bidder_id'], ['bidders.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_registry_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bidder_id', sa.UUID(), nullable=True),
    sa.Column('registry_type', sa.Enum('udyam', 'gst', 'pan', 'epfo_esic', 'nsic', 'dpiit_startup_india', 'cppp_debarment', name='registry_type_enum'), nullable=True),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bidder_id'], ['bidders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('self_check_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bidder_id', sa.UUID(), nullable=True),
    sa.Column('tender_id', sa.UUID(), nullable=True),
    sa.Column('summary_status', sa.Enum('likely_compliant', 'has_gaps', name='self_check_status_enum'), nullable=True),
    sa.Column('gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bidder_id'], ['bidders.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tender_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=True),
    sa.Column('clause_type', sa.String(), nullable=True),
    sa.Column('threshold_value', sa.Numeric(), nullable=True),
    sa.Column('mandatory', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evaluation_id', sa.UUID(), nullable=True),
    sa.Column('officer_id', sa.UUID(), nullable=True),
    sa.Column('ai_recommendation', sa.Enum('qualify', 'disqualify', 'clarify', name='decision_enum'), nullable=True),
    sa.Column('final_decision', sa.Enum('qualify', 'disqualify', 'clarify', name='decision_enum'), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evaluation_id', sa.UUID(), nullable=True),
    sa.Column('rule_name', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pass', 'fail', 'needs_review', name='check_status_enum'), nullable=True),
    sa.Column('extracted_value', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('explanation_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluation_checks')
    op.drop_table('decisions')
    op.drop_table('tender_rules')
    op.drop_table('self_check_sessions')
    op.drop_table('mock_registry_responses')
    op.drop_table('evaluations')
    op.drop_table('bidder_documents')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tenders')
    op.drop_table('bidders')
    # ### end Alembic commands ###
